src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonneRepository::class)]
class Personne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\ManyToOne(inversedBy: 'personnes')]
    private ?Groupe $groupe = null;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: Point::class)]
   
    private Collection $points;

    public function __construct()
    {
        $this->points = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->getNom();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }
    public function getTotal(): ?int
    {
        $t=$this->getPoints();
        $n=0;
        //dd($t);
        foreach($t as $v){
            $n+= $v->getPoint();
        }
        return $n? $n : 0;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Collection<int, Point>
     */
    public function getPoints(): Collection
    {
        return $this->points;
    }

    public function addPoint(Point $point): self
    {
        if (!$this->points->contains($point)) {
            $this->points->add($point);
            $point->setPersonne($this);
        }

        return $this;
    }

    public function removePoint(Point $point): self
    {
        if ($this->points->removeElement($point)) {
            // set the owning side to null (unless already changed)
            if ($point->getPersonne() === $this) {
                $point->setPersonne(null);
            }
        }

        return $this;
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Personne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('groupe')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
            
        ]);
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\Personne1Type;
use App\Repository\PersonneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/personne')]
class PersonneController extends AbstractController
{
    #[Route('/', name: 'app_personne_index', methods: ['GET'])]
    public function index(PersonneRepository $personneRepository): Response
    {
        $personnes=$personneRepository->findAll();

            return $this->render('personne/index.html.twig', [
            'personnes' => $personnes,
        ]);
    }

    #[Route('/new', name: 'app_personne_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PersonneRepository $personneRepository): Response
    {
        $personne = new Personne();
        $form = $this->createForm(Personne1Type::class, $personne);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            $personneRepository->save($personne, true);

            return $this->redirectToRoute('app_personne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personne/new.html.twig', [
            'personne' => $personne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_personne_show', methods: ['GET'])]
    public function show(Personne $personne): Response
    {
        return $this->render('personne/show.html.twig', [
            'personne' => $personne,
        ]);
    }
   

    #[Route('/{id}/edit', name: 'app_personne_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Personne $personne, PersonneRepository $personneRepository): Response
    {
        $form = $this->createForm(Personne1Type::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $personneRepository->save($personne, true);

            return $this->redirectToRoute('app_personne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personne/edit.html.twig', [
            'personne' => $personne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_personne_delete', methods: ['POST'])]
    public function delete(Request $request, Personne $personne, PersonneRepository $personneRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personne->getId(), $request->request->get('_token'))) {
            $personneRepository->remove($personne, true);
        }

        return $this->redirectToRoute('app_personne_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/personne/_delete_form.html.twig
<form method="post" action="{{ path('app_personne_delete', {'id': personne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personne.id) }}">
     <button class="btn px-0 text-danger">Supprimer</button>
</form>

templates/personne/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_label(form.groupe, 'Groupe ') }}
        <div class="input-group">
           
            {{ form_widget(form.groupe, {'attr': {'class': 'form-select'}}) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.nom, 'Nom de la peronne') }}
        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
    </div>
    
    <button class="btn btn-primary my-4">{{ button_label|default('Enrégistrer') }}</button>
{{ form_end(form) }}

templates/personne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Personne{% endblock %}

{% block body %}
    <h1 class="pb-2 border-bottom mb-4">Modifier Personne</h1>

    {{ include('personne/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_personne_index') }}">Retour</a>

    {{ include('personne/_delete_form.html.twig') }}
{% endblock %}

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnes {% endblock %}

{% block body %}
<div class="row"> 
    <div class="col-md-12"> 
    <h1 class="pb-2 border-bottom mb-4">Personnes</h1>
    </div>
<div class="col-md-8"> 

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Groupe</th>
                <th>Points</th>
                <th class="text-end">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personne in personnes %}
            <tr>
                <td>{{ personne.id }}</td>
                <td>{{ personne.nom }}</td>
                <td>{{ personne.groupe }}</td>
                <td>{{ (personne.total) }}</td>
                <td class="text-end">
                    <a class="btn btn-sm btn-primary" href="{{ path('app_point_new', {'id': personne.id}) }}">Ajouter point</a>
                    
                    
                    <a href="{{ path('app_personne_show', {'id': personne.id}) }}">Afficher</a>
                    <a href="{{ path('app_personne_edit', {'id': personne.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Personne(s) trouvées</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_personne_new') }}">Ajouter</a>
</div>
</div>
{% endblock %}

templates/personne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle personne{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-12">
        <h1 class="pb-2 border-bottom mb-4">Nouvelle personne</h1>
    </div>
<div class="col-md-4">
    {{ include('personne/_form.html.twig') }}

    <a class="btn px-0 py-4 " href="{{ path('app_personne_index') }}">Retour</a>
    </div>
    </div>
{% endblock %}

templates/personne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
    <h1 class="pb-2 border-bottom mb-4">Personne</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personne.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ personne.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_personne_index') }}">Retour</a>

    <a href="{{ path('app_personne_edit', {'id': personne.id}) }}">Modifier</a>

    {{ include('personne/_delete_form.html.twig') }}
{% endblock %}